### ISSUE TITLE
(P3) SMILE Teacher Login Panel keyboard input hides the IP address

### ISSUE THREAD

**Issue by truedat101** [RazortoothRTC/smile_teacher_android#33]
This is a regression.  Login panel needs switch to be a scrollview or at least position above the keyboard.  See screenshot below.

**Comment by chrqls** [comment]
What is your device? I don't have this problem on Nexus 7
![screen shot 2014-04-11 at 17 24 26](https://cloud.githubusercontent.com/assets/3521208/2681479/28f1df62-c18e-11e3-97c9-165cbab4cb00.png)

**Comment by truedat101** [comment]
I'm on nexus7 gen 2.  The device has a higher density display.  The Keyboard should push the visible form element above the keyboard.  Should we be using a scrollview container?

![screenshot_2014-04-08-22-07-07](https://cloud.githubusercontent.com/assets/64202/2686508/96917ec2-c208-11e3-99a1-ca26f46a3e3e.png)

**Comment by chrqls** [comment]
Instead of using a scrollview container that would force the teacher to scroll each time he starts the application, I suggest this new interface that should fit with the nexus 7, gen 2.
Here is the interface:
![screenshot_2014-04-14-11-26-38](https://cloud.githubusercontent.com/assets/3521208/2699173/a4616880-c403-11e3-9805-c250013a17c9.png)
Could you test it on yours?

**Comment by truedat101** [comment]
Working ok, verified.  Close
